project_id = "qhbrkcqopqjjaemifjtt"

[functions.ai-assistant]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
